# path: ./docker-compose.yml

version: '3'
services:
  strapi:
    container_name: strapi
    build: .
    image: strapi
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_FILENAME: ${DATABASE_FILENAME}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./.tmp:/opt/app/.tmp
      # - ./config:/opt/app/config
      # - ./src:/opt/app/src
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - strapi

networks:
  strapi:
    name: Strapi
    driver: bridge
